/**
* OpenAPI Generator test with Qiita API
* Qiita API を用いたOpenAPI Generator のテストです。
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.openapigenerationtestapi.sp.model


import com.squareup.moshi.Json
/**
 * Qiita Teamのグループを表します。
 * @param createdAt データが作成された日時
 * @param id グループの一意なIDを表します。
 * @param name グループに付けられた表示用の名前を表します。
 * @param private 非公開グループかどうかを表します。
 * @param updatedAt データが最後に更新された日時
 * @param urlName グループのチーム上での一意な名前を表します。
 */

data class Group (
    /* データが作成された日時 */
    @Json(name = "created_at")
    val createdAt: java.time.OffsetDateTime? = null,
    /* グループの一意なIDを表します。 */
    @Json(name = "id")
    val id: kotlin.Int? = null,
    /* グループに付けられた表示用の名前を表します。 */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* 非公開グループかどうかを表します。 */
    @Json(name = "private")
    val private: kotlin.Boolean? = null,
    /* データが最後に更新された日時 */
    @Json(name = "updated_at")
    val updatedAt: java.time.OffsetDateTime? = null,
    /* グループのチーム上での一意な名前を表します。 */
    @Json(name = "url_name")
    val urlName: kotlin.String? = null
)

