/**
* OpenAPI Generator test with Qiita API
* Qiita API を用いたOpenAPI Generator のテストです。
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.openapigenerationtestapi.sp.model

import com.example.openapigenerationtestapi.sp.model.Tagging

import com.squareup.moshi.Json

/**
 * 
 * @param body Markdown形式の本文
 * @param coediting この記事が共同更新状態かどうか (Qiita Teamでのみ有効)
 * @param groupUrlName この投稿を公開するグループの url_name (null で全体に公開。Qiita Teamでのみ有効)
 * @param private 限定共有状態かどうかを表すフラグ (Qiita Teamでは無効)
 * @param tags 記事に付いたタグ一覧
 * @param title 記事のタイトル
 * @param tweet Twitterに投稿するかどうか (Twitter連携を有効化している場合のみ有効)
 */

data class InlineObject (
    /* Markdown形式の本文 */
    @Json(name = "body")
    val body: kotlin.String? = null,
    /* この記事が共同更新状態かどうか (Qiita Teamでのみ有効) */
    @Json(name = "coediting")
    val coediting: kotlin.Boolean? = null,
    /* この投稿を公開するグループの url_name (null で全体に公開。Qiita Teamでのみ有効) */
    @Json(name = "group_url_name")
    val groupUrlName: kotlin.String? = null,
    /* 限定共有状態かどうかを表すフラグ (Qiita Teamでは無効) */
    @Json(name = "private")
    val private: kotlin.Boolean? = null,
    /* 記事に付いたタグ一覧 */
    @Json(name = "tags")
    val tags: kotlin.collections.List<Tagging>? = null,
    /* 記事のタイトル */
    @Json(name = "title")
    val title: kotlin.String? = null,
    /* Twitterに投稿するかどうか (Twitter連携を有効化している場合のみ有効) */
    @Json(name = "tweet")
    val tweet: kotlin.Boolean? = null
)

