/**
* OpenAPI Generator test with Qiita API
* Qiita API を用いたOpenAPI Generator のテストです。
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.openapigenerationtestapi.sp.model


import com.squareup.moshi.Json

/**
 * 記事に付けられた個々のタグを表します。
 * @param followersCount このタグをフォローしているユーザの数
 * @param iconUrl このタグに設定されたアイコン画像のURL
 * @param id タグを特定するための一意な名前
 * @param itemsCount このタグが付けられた記事の数
 */

data class Tag (
    /* このタグをフォローしているユーザの数 */
    @Json(name = "followers_count")
    val followersCount: kotlin.Int? = null,
    /* このタグに設定されたアイコン画像のURL */
    @Json(name = "icon_url")
    val iconUrl: kotlin.String? = null,
    /* タグを特定するための一意な名前 */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* このタグが付けられた記事の数 */
    @Json(name = "items_count")
    val itemsCount: kotlin.Int? = null
)

