/**
* OpenAPI Generator test with Qiita API
* Qiita API を用いたOpenAPI Generator のテストです。
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.openapigenerationtestapi.sp.model


import com.squareup.moshi.Json

/**
 * 記事とタグとの関連を表します。
 * @param name タグを特定するための一意な名前
 * @param versions 
 */

data class Tagging (
    /* タグを特定するための一意な名前 */
    @Json(name = "name")
    val name: kotlin.String? = null,
    @Json(name = "versions")
    val versions: kotlin.collections.List<kotlin.String>? = null
)

