/**
* OpenAPI Generator test with Qiita API
* Qiita API を用いたOpenAPI Generator のテストです。
*
* The version of the OpenAPI document: 0.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.openapigenerationtestapi.sp.model


import com.squareup.moshi.Json
/**
 * Qiita上のユーザを表します。
 * @param description 自己紹介文
 * @param facebookId Facebook ID
 * @param followeesCount このユーザがフォローしているユーザの数
 * @param followersCount このユーザをフォローしているユーザの数
 * @param githubLoginName GitHub ID
 * @param id ユーザID
 * @param itemsCount このユーザが qiita.com 上で公開している記事の数 (Qiita Teamでの記事数は含まれません)
 * @param linkedinId LinkedIn ID
 * @param location 居住地
 * @param name 設定している名前
 * @param organization 所属している組織
 * @param permanentId ユーザごとに割り当てられる整数のID
 * @param profileImageUrl 設定しているプロフィール画像のURL
 * @param teamOnly Qiita Team専用モードに設定されているかどうか
 * @param twitterScreenName Twitterのスクリーンネーム
 * @param websiteUrl 設定しているWebサイトのURL
 */

data class User (
    /* 自己紹介文 */
    @Json(name = "description")
    val description: kotlin.String? = null,
    /* Facebook ID */
    @Json(name = "facebook_id")
    val facebookId: kotlin.String? = null,
    /* このユーザがフォローしているユーザの数 */
    @Json(name = "followees_count")
    val followeesCount: kotlin.Int? = null,
    /* このユーザをフォローしているユーザの数 */
    @Json(name = "followers_count")
    val followersCount: kotlin.Int? = null,
    /* GitHub ID */
    @Json(name = "github_login_name")
    val githubLoginName: kotlin.String? = null,
    /* ユーザID */
    @Json(name = "id")
    val id: kotlin.String? = null,
    /* このユーザが qiita.com 上で公開している記事の数 (Qiita Teamでの記事数は含まれません) */
    @Json(name = "items_count")
    val itemsCount: kotlin.Int? = null,
    /* LinkedIn ID */
    @Json(name = "linkedin_id")
    val linkedinId: kotlin.String? = null,
    /* 居住地 */
    @Json(name = "location")
    val location: kotlin.String? = null,
    /* 設定している名前 */
    @Json(name = "name")
    val name: kotlin.String? = null,
    /* 所属している組織 */
    @Json(name = "organization")
    val organization: kotlin.String? = null,
    /* ユーザごとに割り当てられる整数のID */
    @Json(name = "permanent_id")
    val permanentId: kotlin.Int? = null,
    /* 設定しているプロフィール画像のURL */
    @Json(name = "profile_image_url")
    val profileImageUrl: kotlin.String? = null,
    /* Qiita Team専用モードに設定されているかどうか */
    @Json(name = "team_only")
    val teamOnly: kotlin.Boolean? = null,
    /* Twitterのスクリーンネーム */
    @Json(name = "twitter_screen_name")
    val twitterScreenName: kotlin.String? = null,
    /* 設定しているWebサイトのURL */
    @Json(name = "website_url")
    val websiteUrl: kotlin.String? = null
)

